### ISSUE TITLE
SSD_TOTAL_GB' exceeded. Limit: 100.0, quotaExceeded

### ISSUE THREAD

**Issue by cmoulliard** [openshift-evangelists/openshifter#15]
When the following config is used against GCE

```
provider: gce
dns:
  zone: europe-west1
  suffix: openshift.mydomain.com

# Generate SSH key pair: e.g. `ssh-keygen -t rsa -b 4096 -C "me@here.com" -f openshift-key`
ssh:
  key: openshift-key

users:
  - username: admin
    password: password
    admin: true
  - username: user
    password: password
    sudoer: true
  - username: user
    password: password
    generic: true
    min: 0
    max: 3

nodes:
  count: 1
  infra: false
  type: n1-standard-1 # See a list of machine types: https://cloud.google.com/compute/docs/machine-types

gce:
  account: demo-384301dab612.json
  # See a list of regions & zones: https://cloud.google.com/compute/docs/regions-zones/regions-zones
  region: us-west1
  zone: us-west1-a
  project: stellar-spark-169312
```
I get this error 

```
INFO[0028] google_compute_firewall.firewall-all: Modifications complete (ID: cluster01-all)  source=Terraform
ERRO[0028] Error applying plan:                     source=Terraform
ERRO[0028]                                               source=Terraform
ERRO[0028] 3 error(s) occurred:                          source=Terraform
ERRO[0028]                                               source=Terraform
ERRO[0028] * google_compute_disk.disk_master_docker: 1 error(s) occurred:  source=Terraform
ERRO[0028]                                               source=Terraform
ERRO[0028] * google_compute_disk.disk_master_docker: Error creating disk: googleapi: Error 403: Quota 'SSD_TOTAL_GB' exceeded. Limit: 100.0, quotaExceeded  source=Terraform
ERRO[0028] * google_compute_disk.disk_master_root: 1 error(s) occurred:  source=Terraform
ERRO[0028]                                               source=Terraform
ERRO[0028] * google_compute_disk.disk_master_root: Error creating disk: googleapi: Error 403: Quota 'SSD_TOTAL_GB' exceeded. Limit: 100.0, quotaExceeded  source=Terraform
ERRO[0028] * google_compute_disk.disk_node_root: 1 error(s) occurred:  source=Terraform
ERRO[0028]                                               source=Terraform
ERRO[0028] * google_compute_disk.disk_node_root: Error creating disk: googleapi: Error 403: Quota 'SSD_TOTAL_GB' exceeded. Limit: 100.0, quotaExceeded  source=Terraform
ERRO[0028]                                               source=Terraform
ERRO[0028] Terraform does not automatically rollback in the face of errors.  source=Terraform
ERRO[0028] Instead, your Terraform state file has been partially updated with  source=Terraform
ERRO[0028] any resources that successfully completed. Please address the error  source=Terraform
ERRO[0028] above and apply again to incrementally change your infrastructure.  source=Terraform
INFO[0028] Terraform finished
INFO[0028] Gathering cluster information
```

Is it possible to specify the SSD_TOTAL as it exceeds ?

What is strange is that the quota defined for my account is 100 Gb
![screenshot 2017-05-31 14 57 01](https://cloud.githubusercontent.com/assets/463790/26632767/81495356-4611-11e7-83ce-1f06119319a5.png)
