### ISSUE TITLE
Allow for fixed password to generated list of users

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/openshifter#32]
RFE for the python version:

Instead of creating users with same username and password, allow to provide configure how the password will be assembled.

New yaml:

```
users: # creates user and associated project named as the user
  - username: admin
    password: password
    admin: true # cluster-admin role
  - username: user
    password: password
    sudoer: true
    execute:
      - new-app mjelen/example # execute in the context of user project
  - username: user
    password: password
    password-type: fixed # Uses the same password for all. Values (fixed, index, user) 
    generic: true # generates user0 up to user3 with password0 up to password3
    min: 0
    max: 3
```

PROPOSAL:

New field:
* *password-type*: fixed # (fixed, index, user) 

Values:
* *fixed*: The value stated in password is the value used for password to every user
* *index*: The value used in password is the "prepend" value and then with index (e.g: password01, password02)
* *user*: Same password as username

Default value: 
* *index*, to preserve compatibility.
