### ISSUE TITLE
Password for subscription manager is in plaintext in the .yml file, should be interactively queried, or encrypted

### ISSUE THREAD

**Issue by jirikolar** [openshift-evangelists/openshifter#54]
Password for subscription manager is in plaintext in the .yml file, should be interactively queried, or encrypted..

**Comment by jorgemoralespou** [comment]
@jirikolar would injecting the value in the yaml from an ENV be sufficient?

e.g.

```
name: cluster-name
bastion: false 
provider: gce
type: origin
release: v3.6.1 
installer: ansible

rhsm:
  username: $USERNAME
  password: $PASSWORD
  pool: $POOLID
```

So you can do:

```
export USERNAME=jiri
export password=mypassword
export POOLID=xxxxx

docker run .... openshifter
```

**Comment by marekjelen** [comment]
IMHO container does not inherit env variables from the current context, so you would need something like

```
export EV="-e USERNAME=jiri"
export EV= $EV -e PASSWORD=password"
export EV="$EV -e POOLID=xxxxx"

docker run $EV ... openshifter
```

however, pyyaml does not resolve env vars, so we would need to make some magic, like using jinja

```
rhsm:
  username: {{ USERNAME }}
  password: {{ PASSWORD }}
  pool: {{ POOLID }}
```
