### ISSUE TITLE
Add documentation for installer:ocu 

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/openshifter#65]
We need to have a valid example with the configuration that can be used when installer is ocu

**Comment by marekjelen** [comment]
```
provider: gce
type: origin
release: v3.7
installer: ocu

dns:
  provider: nip

ssh:
  key: <filename>

gce:
  account: <something>
  region: <region>
  zone: <zone>
  project: <something>
```
